### ISSUE TITLE
2019年10月22日你要记录点什么？

### ISSUE THREAD

**Issue by koala-coding** [koala-coding/day-day-up#2]
2019年10月22日你要记录点什么？

**Comment by sweetXiaoyan** [comment]
### 手写一个loading动画, 摆脱gif
**html**
```html
<div class="loading"></div>
```

**css**
 ```css
 @keyframes loading-spin {
  0% {
    transform: rotate(0deg);
  }
  100% {
    transform: rotate(360deg);
  }
}
.loading {
  display: inline-block;
  border: 4px solid rgba(0, 0, 0, 0.1);
  border-left-color: #eb734a;
  border-radius: 50%;
  width: 40px;
  height: 40px;
  animation: loading-spin 1.2s linear infinite;
}
```
**demo**

![demo](http://img.xiaogangzai.cn/loading.gif)

codepen链接: [https://codepen.io/xiaoxiao_1/pen/xxxgyEy](https://codepen.io/xiaoxiao_1/pen/xxxgyEy)
