### ISSUE TITLE
2020年01月08日你要记录点什么？(简单理解下 http2 的多路复用)

### ISSUE THREAD

**Issue by koala-coding** [koala-coding/day-day-up#27]

**Comment by 592837154** [comment]
#### css基础😉😉😉
##### 水平居中
1. 文本、行内块, text-align: center;
2. width: 100px; margin: 0 auto;
3. text-align: center; + display: inline-block;
4. 绝对定位+transform
5. flex

##### 垂直居中
1. 单行: height + line-height;
2. 多行: height + n * line-height;
3. 图片: vertical-align: middle;
4. display: table-cell;vertical-align: middle;
5. display: flex; flex-direction: column;justify-content: center;
6. 绝对定位+transform
7. display: flex;+ align-self: center;

##### 绝对居中
```css
position: absolute;
    margin: auto;
    width: 100px;
    height: 50px;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
```
##### 两列布局
左列定宽,右列自适应: 左侧定宽,右侧flex:1;
##### 九宫格布局
```css
#parent {
    width: 1200px;
    height: 500px;
    margin: 0 auto;
    display: grid;
    grid-template-columns: repeat(3, 1fr); /*等同于1fr 1fr 1fr,此为重复的合并写法*/
    grid-template-rows: repeat(3, 1fr);  /*等同于1fr 1fr 1fr,此为重复的合并写法*/
}
.item {
    border: 1px solid #000;
}
```
##### 栅格
```css
@media screen and (max-width: 768px) {
 ...
}
@media screen and (min-width: 768px) {
 ...
}
```
### 纯css实现顶部滚动条😉😉😉
[文档](https://juejin.im/post/5c35953ce51d45523f04b6d2)
```
export default function () {
  return (
    <div className={styles.normal}>
      <div className={styles.item}>111</div>
      <div className={styles.item}>111</div>
      .
      .
      .
      <div className={styles.item}>111</div>
    </div>
  );
}
```
```css
.normal {
  background-image: linear-gradient(to right top, #ffcc00 50%, #eee 50%);
  background-size: 100% calc(100% - 100vh + 5px);
  background-repeat: no-repeat;
}

.item {
  position: relative;
  height: 50px;
  z-index: 1;
}

.normal::after {
  content: "";
  position: fixed;
  top: 5px;
  left: 0;
  bottom: 0;
  right: 0;
  background: #fff;
  z-index: 0;
}
```

```
background-image可以给dom配置多个背景图和背景色
background-size可以修饰background-image,两者的参数位置一一对应
linear-gradient渐变
```
### 一个div画出一个棋盘😉😉😉
```css
.box {
  font-size: 50px;
  width: 6em;
  background-color: green;
  height: 4em;
  background-image:
    linear-gradient(to bottom, transparent 95%, white 95%),
    linear-gradient(to right, transparent 95%, white 95%),
    linear-gradient(to top, transparent 95%, white 95%),
    linear-gradient(to left, transparent 95%, white 95%);
  background-size: 1em 1em;
  background-repeat: repeat, repeat, repeat-x, repeat-y;
}
```
![](data:image/jpeg;base64,/9j/4QlQaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wLwA8P3hwYWNrZXQgYmVnaW49Iu+7vyIgaWQ9Ilc1TTBNcENlaGlIenJlU3pOVGN6a2M5ZCI/PiA8eDp4bXBtZXRhIHhtbG5zOng9ImFkb2JlOm5zOm1ldGEvIiB4OnhtcHRrPSJBZG9iZSBYTVAgQ29yZSA1LjYtYzEzOCA3OS4xNTk4MjQsIDIwMTYvMDkvMTQtMDE6MDk6MDEgICAgICAgICI+IDxyZGY6UkRGIHhtbG5zOnJkZj0iaHR0cDovL3d3dy53My5vcmcvMTk5OS8wMi8yMi1yZGYtc3ludGF4LW5zIyI+IDxyZGY6RGVzY3JpcHRpb24gcmRmOmFib3V0PSIiLz4gPC9yZGY6UkRGPiA8L3g6eG1wbWV0YT4gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8P3hwYWNrZXQgZW5kPSJ3Ij8+/+0ALFBob3Rvc2hvcCAzLjAAOEJJTQQlAAAAAAAQ1B2M2Y8AsgTpgAmY7PhCfv/bAIQAGBYWIhgiNyAgN0IvKi9CQDU0NDVARkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRgEaIiIsJiw1ISE1RjUsNUZGRjs7RkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZG/90ABAAH/+4ADkFkb2JlAGTAAAAAAf/AABEIAFgAZAMAIgABEQECEQH/xACSAAEAAwEBAQAAAAAAAAAAAAAAAwQFAQIGAQEBAAMBAAAAAAAAAAAAAAAABAEDBQYQAAIBAgIDDAkFAQAAAAAAAAABAgMRBBIxUWETISIyM0FCUmJxcrEFFFOCkZKhwtEjQ4GistIRAAEDAAcHBAMBAAAAAAAAAAABAhEDEhQhMkFRBBMxgZGh4SJiscEzYXHR/9oADAMAAAERAhEAPwDRABaeYAAAAAAAAAAAAAAAAAAP/9DROSlGCvJqK0b50p+kOSXiXkymkcrWq5DztE1HOqu4XllVqTdlON3tDrUk7OcfiYlHlI+KPmeavHl4n5klodHBCzcMib+vg3t1p2zZ42va9+c87vS68fiZH7Hv/aVxaHaIFoGfvr4PoZVacXZzimtoVWm02pxstO/rMXFctPvO0+Sqe55sWh05GdwyYv6+DX3el7SPxPUqtOLtKcU+8+eZYxfKy/j/AChaHRwQxuGRN/XwbUZwnfJKMmtTOmZ6N48/D9yNMqonq9tZSWmYjFRG6f6AAbTQf//R0StjZ5KSdk+F0lfmZZK2NhnpJXS4XSduZlFLgU4FB+ROfwUKVe9SKyQ4y6O05Ur2nJZIaX0dp2lQtOLzw40eltOVKF5yeeGl9Lac2+Dp+qCTd/0b5Icfq9kg9Y7EPlJ9w/Rtmhx+t2SD1ftw+YyshaxNiK9qslkhp6p2Fe9KbyQ3snR2s5iKF6snnhp6x2FC1KazQ38nS2sXyZvkgeI7EPlJ8TXy1WskHo0x7KIHh+3D5yfE0M1VvNBaNMuyhfBj1QTYCrnlJZYrg9GNudF8oYClklJ5ovg9GV+dF8uoMN+pz9pxJOn2oABQSH//0tEp+kOSXiXky4VsbJRpJtKXCWnuepo302BTz9BjTn8GTR5SPij5nKvHl4n5k9KsnUiskeNHXr8QqVkpy4ENL16/Ec3I6UJB5/Y9/wC0rl3dVuN8kePt6veQ7svZw/t/0FColwxXLT7ztPkqnuebJcTVSqyWSL39v5EKq3KbyR6GvW9pnMzmvMpMsYvlZfx/lHl1l7OH9v8AosYqqlVayRejX1VtMZGISD16N48/D9yNMoYCopSklGMeDzX1rW2Xy/Z8HMg2jEn8+1AAKSU//9PRK+MpSq01GCu81/oywCtzayVTzjHVHVjJpYOtGcW47yknpWvvOVMHWcpNR3m3zrX3muCezt1UotGVXuZfqlbccuXfz3tdaMveQ+pV+r9V+TaAs7dVFo9vcy8RhK06kpRjdN61+RDCVlTnFx33ltvrmb2moBZ01Fpzq9zFeCr9X6r8k+JwlWdRyjG63udaltNMCzt1UWj29yjgsPUpSk5qycbaVrReANzGIxKqGikfXWYgAA2Go//U0QAWnmAAAAAAAAAAAAAAAAAAD//Z)
